/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/base/button/BaseButton.vue')['default']
    BaseFilter: typeof import('./src/components/filter/BaseFilter.vue')['default']
    BaseIcon: typeof import('./src/components/base/icon/BaseIcon.vue')['default']
    BasePagination: typeof import('./src/components/base/pagination/BasePagination.vue')['default']
    BasePopup: typeof import('./src/components/base/popup/BasePopup.vue')['default']
    BaseTab: typeof import('./src/components/base/tab/BaseTab.vue')['default']
    BaseTable: typeof import('./src/components/base/table/BaseTable.vue')['default']
    DropdownSort: typeof import('./src/components/filter/DropdownSort.vue')['default']
    EmptyBlock: typeof import('./src/components/base/empty/EmptyBlock.vue')['default']
    IEpLoading: typeof import('~icons/ep/loading')['default']
    MoreToken: typeof import('./src/components/others/MoreToken.vue')['default']
    PopperFilter: typeof import('./src/components/filter/PopperFilter.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./src/components/layout/TheHeader.vue')['default']
    TheLayout: typeof import('./src/components/layout/TheLayout.vue')['default']
    ThePageLoading: typeof import('./src/components/loading/ThePageLoading.vue')['default']
    TheSidebar: typeof import('./src/components/layout/TheSidebar.vue')['default']
  }
}
